baseURL = "http://example.org/"
languageCode = "de-de"
title = "Wedding Singer Demo"
theme = "sonja"

[params]
  description = "Demo site for wedding-singer theme"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

