language: python

go:
  - master

sudo: false

script:
  - rm -rf public
  - ./bin/hugo -v

deploy:
  provider: pages
  local-dir: public
  target-branch: master
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  on:
    branch: src

