baseURL = "https://sonjaeisenreich.github.io/"
languageCode = "de-de"
title = "Sonja Maria Eisenreich"
theme = "hugo-split-theme"

[menu]
  [[menu.footer]]
  weight = 5
  name = "Impressum und Datenschutz"
  url = "/impressum"

  [[menu.main]]
  weight = 5
  name = "Bildergalerie"
  url = "/about/Bildergalerie"

  [[menu.main]]
  weight = 5
  name = "Events"
  url = "/venues"

  [[menu.main]]
  weight = 5
  name = "Hörproben"
  url = "/about/Hörproben"

[params]

  # Metadata for search engines and social sharing
  author = "Sonja Maria Eisenreich"
  description = "Split is a centrally-divided layout for a professional online presence with a big image or video left with alongside content."
  shareImage = "images/social.jpg"
  twitterHandle = "onepagelove"

  custom.css.enable = true

  # Favicon
  favicon = "favicon.ico"

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "img/Sonja.png"
      position = "center center"

    # Video
    [params.visual.video]
      enable = false

  # Links
  #
  # Links List #1
  [[params.links]]
    [params.links.list1]
      heading = "Connect"

      [[params.links.list1.link]]
        text = "Blog"
        url = "#"
        new_tab = true # new tab

      [[params.links.list1.link]]
        text = "Email"
        url = "#"
        new_tab = false # Default, open at same tab

      [[params.links.list1.link]]
        text = "Newsletter"
        url = "#"

  # Links List #2
  [[params.links]]
    [params.links.list2]
      heading = "Social"

      [[params.links.list2.link]]
        text = "Twitter"
        url = "#"

      [[params.links.list2.link]]
        text = "Instagram"
        url = "#"

      [[params.links.list2.link]]
        text = "Dribbble"
        url = "#"

  # Links List #3
  [[params.links]]
    [params.links.list3]
      heading = "Network"

      [[params.links.list3.link]]
        text = "Link One"
        url = "#"

      [[params.links.list3.link]]
        text = "Link Two"
        url = "#"

      [[params.links.list3.link]]
        text = "Link Three"
        url = "#"

  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://onepagelove.com/split

[server]
[[server.headers]]
    for = '/**'
    [server.headers.values]
      Content-Security-Policy = "default-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' https://dummyimage.com"
      Referrer-Policy = 'strict-origin-when-cross-origin'
      X-Content-Type-Options = 'nosniff'
      X-Frame-Options = 'DENY'
      X-XSS-Protection = '1; mode=block'
