baseURL = "http://example.org/"
languageCode = "de-de"
title = "Wedding Singer Demo"
theme = "sonja"

[params]
  description = "Demo site for wedding-singer theme"

[[menu.footer]]
  name = "🔗 Instagram"
  url = "https://www.instagram.com/saengerin_sonja/"
  weight = 1

[markup.goldmark.renderer]
  unsafe= true

