baseURL = "https://sonjaeisenreich.github.io/"
languageCode = "en-us"
title = "Sonja Maria Eisenreich"
theme = "airspace"

[menu]
  [[menu.footer]]
  weight = 5
  name = "Impressum und Datenschutz"
  url = "/impressum"

[params]
  [params.slider]
    enable = true
    title = "Sonja Maria Eisenreich"
    subtitle = "Zu jedem Anlass die passende Musik"
	
  [params.wrapper]
    enable = true
    title = "Meine Musik für Ihre Veranstaltung"
    italic = "Soll auch Ihre Feier unvergesslich werden? Dann sind Sie hier genau richtig!"
    paragraph = "Seit einigen Jahren bereichere ich diverse Feiern mit meiner Stimme, meinem Saxophon- oder Klarinettenspiel. Mein großes Repertoire, das von klassischer Musik über Jazz bis hin zu Musical und Pop reicht, erweitere ich für Ihr Programm gerne um Ihr Lieblingslied. Hauptsächlich spiele und singe ich zu meinen Playbacks, auf Wunsch organisiere ich aber auch gerne einen Pianisten oder Organisten. Mit meiner Musikanlage kann ich bei Bedarf auch große Räume ausfüllen."
    
  [params.feature]
    enable = true
    title = "Mein Repertoire"
    content = "Ich habe eine klassische Gesangsausbildung und singe dadurch gerne und viel Oper und Operette. Schon während meiner Ausbildung habe ich aber gemerkt, dass mir auch andere Musikrichtungen wie Jazz oder Musicals sehr gefallen. Abgerundet mit modernen Hits habe ich ein sehr vielfältiges Repertoire mit Songs von Whitney Houston, Norah Jones, Leonard Cohen und vielen anderen, Jazzstandards wie How High the Moon, Girl from Ipanema, Take the A-Train sowie Musical- und Operettenstücke aus Das Phantom der Oper, Die Lustige Witwe, Porgy and Bess und vielen anderen."

  [params.call]
    enable = true
    title = "Kontakt."
    paragraph = "Bitte kontaktieren Sie mich telefonisch unter 01573 7908747 oder per E-Mail unter SonjaEisenreich@hotmail.de."
